/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XFNdtJtzvXI
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Configuration() {
  return (
    <Card className="bg-[#f2f2f2] h-full w-1/2 p-6 rounded-lg shadow-lg text-center">
      <CardHeader>
        <CardTitle className="text-2xl text-[#D91966]">Configuracion</CardTitle>
        <CardDescription className="text-xl">Notificaciones por mail</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4 px-32">
        <div className="flex p-4 space-x-4">
          <Switch id="all" />
          <Label className="text-center" htmlFor="all">
            Activar/Desactivar todas
          </Label>
        </div>
        <div className="bg-[#fefefe] p-4 rounded-lg space-y-6">
          <div className="flex justify-start items-center space-x-4">
            <Switch id="option1"  />
            <Label className="text-center" htmlFor="option1">
              Inscripción pendiente
            </Label>
          </div>
          <div className="flex justify-start items-center space-x-4">
            <Switch id="option2" />
            <Label className="text-center" htmlFor="option2">
              Recordar review
            </Label>
          </div>
          <div className="flex justify-start items-center space-x-4">
            <Switch id="option3" />
            <Label className="text-center" htmlFor="option3">
              Cierre de menú
            </Label>
          </div>
        </div>
        <div className="space-y-2">
          <Input id="currentPassword" required type="password" placeholder="Contraseña"/>
        </div>
        <div className="space-y-2">
          <Input id="newPassword" required type="password" placeholder="Confirmar contraseña"/>
        </div>
        <Button className="w-1/2 bg-[#D91966] text-gray-50">Guardar Cambios</Button>
      </CardContent>
    </Card>
  )
}
