/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XFNdtJtzvXI
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Configuration() {
  return (
    <Card className="bg-[#f2f2f2] h-full w-full p-6 rounded-lg shadow-lg text-center">
      <CardHeader>
        <CardTitle className="text-6xl text-[#D91966]">Configuracion</CardTitle>
        <CardDescription className="text-5xl">Notificaciones por mail</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex justify-center items-center space-x-4">
          <Switch className="bg-[#D91966]" id="all" />
          <Label className="text-center" htmlFor="all">
            Activar/Desactivar todas
          </Label>
        </div>
        <div className="bg-[#fefefe] p-6 rounded-lg space-y-6 mx-auto w-1/2">
          <div className="flex justify-start items-center space-x-4">
            <Switch className="bg-[#D91966]" id="option1" />
            <Label className="text-center" htmlFor="option1">
              Option 1
            </Label>
          </div>
          <div className="flex justify-start items-center space-x-4">
            <Switch className="bg-[#D91966]" id="option2" />
            <Label className="text-center" htmlFor="option2">
              Option 2
            </Label>
          </div>
          <div className="flex justify-start items-center space-x-4">
            <Switch className="bg-[#D91966]" id="option3" />
            <Label className="text-center" htmlFor="option3">
              Option 3
            </Label>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="currentPassword">Current Password</Label>
          <Input id="currentPassword" required type="password" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="newPassword">New Password</Label>
          <Input id="newPassword" required type="password" />
        </div>
        <Button className="w-full">Confirm</Button>
      </CardContent>
    </Card>
  )
}
